---
title: "Recommendation of harder styles music on Spotify"
author: "Szymon Bujowski"
date: "5/12/2022"
abstract: "The following case study was carried out as part of Machine Learning course classes at Poznan University of Technology. It concerns applying (...) classifiers to the dataset containing Spotify's data on songs belonging to the harder music styles (such as Techno, Hardstyle, Hardcore, Gabber, etc.) with a goal of creating a good recommendations system for such songs. Creation of such system could potentially invoke improvement of the current recommendations system and would be a workaround to satisfy my personal music taste needs. Reuslts of the case study concluded (...)"
output:
  html_document:
    toc: yes
    number_sections: yes
    toc_float: yes
    theme: united
    highlight: tango
  pdf_document:
    toc: yes
always_allow_html: true
---

```{r setup, include=FALSE}
# add stuff if needed
```

`TODO` - add used classifiers to the abstract
`TODO` - add short one-sentence results summary to the abstract

# Introduction

The following case study was created 

`TODO` - the context, the "behind", the "why", the personal connection, the "what"

`TODO` - extract and use in README

# Dataset

## Rough data

`TODO` - detailed description of the dataset and its characteristics

- short description of the dataset (where does it come from, how obtained, etc.)
- examples from the dataset
- interpretation of the attributes
  - types
  - meaning
  - histograms
  - correlations
  - etc.

## Hypothesis

`TODO` - the three (or more?) possible hypothesis
`TODO` - posed classification question

What I presume:
- Spotify recommendations system sucks and could work better
- not enough attributes for specifically harder styles
- I'm too picky

## Cleaning

`TODO` - fill in section if cleaning was done, otherwise remove

## Preprocessing

`TODO` - how the data was preprocessed

- manual removal of unnecessary attributes (possibly by merging them, e.g. artist with title to form "just descriptive" one)
- (possibly) division into subsets (if something interesting across some specific subset)
- making data "nicer" - discretization, etc.

# Classification

`TODO` - main stuff, the juice, the ganja

## Classifier 1

`TODO`

- description
- parameters
- used software/tools
- show & interpret all the interesting knowledge induced by this approach

## Classifier 2

`TODO`

## Classifier 3

`TODO`

## Classifier (?)

`TODO` - add more classifiers if used, remove if just three

## Comparison

`TODO` - comparison of all the above approaches



`TODO` - distinction between classifying the whole thing and the subsets (if they exist)

# Classifiers in practice

`TODO` - apply the classifiers to a new *discover weekly* Spotify's list, check if they did better job than it

# Conclusions

`TODO`
